# Site configuration
name: Daniel Pillis
avatar: images/circle_bw_crop.jpg

# Footer links (only include those in use)
footer-links:
  email: dpillis@gmail.com
  github: dpillis
  instagram: dpillis
  rss: true
  # linkedin:
  # twitter:
  # youtube:
  # stackoverflow:

# Site URL for sitemap and RSS
url: "http://dpillis.github.io"
baseurl: "/dpillis-htmaa"  # Keep empty for user/organization pages

# permalink: /:title/
permalink: /

# Theme & Jekyll version tracking
version: v1.2.0

# Markdown and syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-sitemap
  # - jekyll-feed

# Optional
# excerpt_separator: <!--more-->
# disqus:
# google_analytics:

# Excluded from build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/
